app = "telegram-dota-bot"
     primary_region = "ams"

     [[services]]
       internal_port = 8080
       protocol = "tcp"
       auto_stop_machines = false
       auto_start_machines = true
       min_machines_running = 1
